name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      # Java 17 é necessário para as ferramentas modernas do Android SDK (2026)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup /home/runner/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib --never install flixel 4.11.0
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install tjson
          haxelib install hxIni
          # Instalando bibliotecas via Git sem o sufixo .git para evitar erros de clone
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib git hxCodec https://github.com/MAJigsaw77/hxCodec
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0 -y
          haxelib set openfl 9.1.0 -y
          haxelib set flixel 4.11.0 -y
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -release

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Baldi-Android-Build
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
